### ISSUE TITLE
Adding flags to the (sbatch) submit command

### ISSUE THREAD

**Issue by Dunrar** [brentp/slurmpy#8]
Hey, I am trying to add the --wait flag to the sbatch submit command. I tried s.run(_cmd="sbatch --wait"), but that did not work. Thank you!

**Comment by Dunrar** [comment]
Okay, I guess I could just do s = Slurm("job-name", {"W": "", "partition": "my-partition"})

**Comment by ManavalanG** [comment]
Relevant comment - https://github.com/brentp/slurmpy/issues/13#issuecomment-4623873964
